COMMON_FLAGS: &COMMON_CMD
  flash-attn: true
  cache-type-k: q8_0
  cache-type-v: q8_0

QWEN_SAMPLING: &QWEN_SAMPLING
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 20

GEMMA_SAMPLING: &GEMMA_SAMPLING
  temp: 1.0
  min-p: 0.01
  top-p: 0.95
  top-k: 64
  repeat-penalty: 1.0

MISTRAL_SAMPLING: &MISTRAL_SAMPLING
  temp: 0.15

QWQ_SAMPLING: &QWQ_SAMPLING
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 40
  repeat-penalty: 1.1
  dry-multiplier: 0.5
  samplers: top_k;top_p;min_p;temperature;dry;typ_p;xtc

GLM_SAMPLING: &GLM_SAMPLING
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 20

healthCheckTimeout: 60

logLevel: info

models:
  Qwen3-8B-Q4_K_M:
    hf_tokenizer_for_model: Qwen/Qwen3-8B
    supports_no_think_toggle: true
    sampling: *QWEN_SAMPLING
    aliases: [Qwen3-8B-NoThink]
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-8B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  Qwen3-30B-A3B:
    hf_tokenizer_for_model: Qwen/Qwen3-30B-A3B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-30B-A3B-Q4_K_M.gguf
      ctx-size: 40960
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  Qwen3-32B-Think:
    hf_tokenizer_for_model: Qwen/Qwen3-32B
    sampling: *QWEN_SAMPLING
    aliases: [Qwen3-32B-NoThink]
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  Qwen3-0.6B:
    hf_tokenizer_for_model: Qwen/Qwen3-0.6B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-0.6B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  # Qwen3-32B-UD-Q4:
  #   hf_tokenizer_for_model: Qwen/Qwen3-32B
  #   sampling: *QWEN_SAMPLING
  #   cmd:
  #     <<: *COMMON_CMD
  #     bin: llama.cpp/build/bin/llama-server
  #     port: ${PORT}
  #     model: ./models/Qwen3-32B-UD-Q4_K_XL.gguf
  #     ctx-size: 16384
  #     gpu-layers: auto
  #     threads:    auto
  #     reasoning-format: deepseek
  #     parallel: 1

  Qwen3-4B-Q4-Bart:
    hf_tokenizer_for_model: Qwen/Qwen3-4B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen_Qwen3-4B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  Qwen3-32B-SpeculativeDecoding-32768:
    hf_tokenizer_for_model: Qwen/Qwen3-32B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-32B-Q4_K_M.gguf
      ctx-size: 32768
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      model-draft: ./models/Qwen3-0.6B-Q4_K_M.gguf
      gpu-layers-draft: 99
      device-draft: auto
      ctx-size-draft: 8192
      parallel: 1

  Qwen3-8B-Q4_K_M-Bart:
    hf_tokenizer_for_model: Qwen/Qwen3-8B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-8B-Q4_K_M-Bart.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  GLM-4-32B-0414:
    hf_tokenizer_for_model: THUDM/GLM-4-32B-0414
    sampling: *GLM_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/GLM-4-32B-0414-Q4_K_M.gguf
      ctx-size: 8192
      gpu-layers: auto
      threads:    auto
      override-kv: tokenizer.ggml.eos_token_id=int:151336
      override-kv: glm4.rope.dimension_count=int:64
      chat-template: chatglm4
      parallel: 1

  gemma-3-1b-it:
    hf_tokenizer_for_model: google/gemma-3-1b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-1b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      chat-template: gemma
      parallel: 1

  gemma-3-4b-it:
    hf_tokenizer_for_model: google/gemma-3-4b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-4b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      chat-template: gemma
      parallel: 1

  gemma-3-12b-it:
    hf_tokenizer_for_model: google/gemma-3-12b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-12b-it-q4_0.gguf
      ctx-size: 8192
      gpu-layers: auto
      threads: auto
      chat-template: gemma
      parallel: 1

  gemma-3-27b-it:
    hf_tokenizer_for_model: google/gemma-3-27b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-27b-it-q4_0.gguf
      ctx-size: 8192
      gpu-layers: auto
      threads:    auto
      chat-template: gemma
      parallel: 1

  Mistral-Small-3.1-24B:
    hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
    sampling: *MISTRAL_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf
      ctx-size: 8192
      gpu-layers: auto
      threads:    auto
      parallel: 1

  QwQ-32B-Q4_K_M:
    hf_tokenizer_for_model: Qwen/QwQ-32B
    sampling: *QWQ_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/QwQ-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      parallel: 1

  # gemma-3-27b-it-SpeculativeDecoding:
  #   hf_tokenizer_for_model: google/gemma-3-27b-it
  #   sampling: *GEMMA_SAMPLING
  #   cmd:
  #     <<: *COMMON_CMD
  #     bin: llama.cpp/build/bin/llama-server
  #     port: ${PORT}
  #     model: ./models/gemma-3-27b-it-q4_0.gguf
  #     ctx-size: 8192
  #     gpu-layers: auto
  #     threads:    auto
  #     model-draft: ./models/gemma-3-1b-it-q4_0.gguf
  #     gpu-layers-draft: 99
  #     device-draft: Metal
  #     ctx-size-draft: 2048
  #     chat-template: gemma
  #     parallel: 1

  Qwen3-30B-A3B-UD:
    hf_tokenizer_for_model: Qwen/Qwen3-30B-A3B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-30B-A3B-UD-Q4_K_XL.gguf
      ctx-size: 40960
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  Qwen3-32B-SpeculativeDecoding-16384:
    hf_tokenizer_for_model: Qwen/Qwen3-32B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      model-draft: ./models/Qwen3-0.6B-Q4_K_M.gguf
      gpu-layers-draft: 99
      device-draft: Metal
      ctx-size-draft: 8192
      parallel: 1

  Mistral-Small-3.1-24B-SpeculativeDecoding:
    hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
    sampling: *MISTRAL_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Mistral-Small-3.1-24B-Instruct-2503-Q4_K_M.gguf
      ctx-size: 8192
      gpu-layers: auto
      threads:    auto
      model-draft: ./models/alamios_Mistral-Small-3.1-DRAFT-0.5B-Q5_K_L.gguf
      gpu-layers-draft: 99
      device-draft: Metal
      ctx-size-draft: 2048
      parallel: 1

  OpenCodeReasoning-Nemotron-32B-IOI:
    hf_tokenizer_for_model:   nvidia/OpenCodeReasoning-Nemotron-32B-IOI
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/OpenCodeReasoning-Nemotron-32B-IOI-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1

  DeepSeek-R1-0528-Qwen3-8B-UD-Q4_K_XL:
    hf_tokenizer_for_model: Qwen/Qwen3-8B
    sampling: *QWEN_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/DeepSeek-R1-0528-Qwen3-8B-UD-Q4_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      parallel: 1