startPort: 20000
COMMON_FLAGS:
  port: ${PORT}
  bin: llama.cpp/build/bin/llama-server
  cache-type-k: q8_0
  cache-type-v: q8_0
  jinja: true
  parallel: 1
  cont-batching: true
  gpu-layers: auto
  threads: auto
QWEN3_SAMPLING: &id001
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 20
GPTOSS_SAMPLING: &id008
  temp: 1
  top-p: 1.0
  top-k: 0
GLM45_SAMPLING: &id009
  temp: 0.6
  top-p: 1.0
  top-k: 0
healthCheckTimeout: 60
logLevel: info
models:
  gpt-oss-20b-Q8-med:
    hf_tokenizer_for_model: ./models/tokenizers/openai/gpt-oss-20b
    sampling: *id008
    cmd:
      model: ./models/gpt-oss-20b-UD-Q8_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
  gpt-oss-120b-Q4-med:
    hf_tokenizer_for_model: ./models/tokenizers/openai/gpt-oss-20b
    sampling: *id008
    cmd:
      model: ./models/gpt-oss-120b-UD-Q4_K_XL-00001-of-00002.gguf
      ctx-size: 16384
      n-predict: 16384
      chat-template-kwargs: '{"reasoning_effort":"medium"}'
  GLM-4.5-Air-Q3:
    hf_tokenizer_for_model: ./models/tokenizers/zai-org/GLM-4.5-Air
    sampling: *id009
    cmd:
      model: ./models/GLM-4.5-Air-Q3_K_S.gguf
      ctx-size: 64000
      n-predict: 64000
  ERNIE-4.5-21B-A3B:
    hf_tokenizer_for_model: ./models/tokenizers/baidu/ERNIE-4.5-21B-A3B-PT
    cmd:
      model: ./models/ERNIE-4.5-21B-A3B-PT-UD-Q5_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
  Apriel-1.5-15b-Thinker:
    hf_tokenizer_for_model: ./models/tokenizers/ServiceNow-AI/Apriel-1.5-15b-Thinker
    sampling:
      temp: 0.6
    cmd:
      model: ./models/Apriel-1.5-15b-Thinker-UD-Q5_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: 99
      threads: 28
  GLM-4.7-Flash:
    hf_tokenizer_for_model: ./models/tokenizers/zai-org/GLM-4.5-Air
    sampling:
      temp: 1
      top-p: 0.95
      top-k: 0
    cmd:
      model: ./models/GLM-4.7-Flash-UD-Q6_K_XL.gguf
      ctx-size: 131072
      n-predict: 131072
  Qwen3.5-35B-A3B-UD-Q4_K_XL:
    hf_tokenizer_for_model: ./models/tokenizers/Qwen/Qwen3.5-35B-A3B
    sampling: *id001
    cmd:
      cache-type-k: f16
      cache-type-v: f16
      model: ./models/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf
      ctx-size: 131072
      n-predict: 131072
  Qwen3.5-27B-UD-Q5_K_XL:
    hf_tokenizer_for_model: ./models/tokenizers/Qwen/Qwen3.5-27B
    sampling: *id001
    cmd:
      cache-type-k: f16
      cache-type-v: f16
      model: ./models/Qwen3.5-27B-UD-Q5_K_XL.gguf
      ctx-size: 32000
      n-predict: 32000
  Qwen3.5-122B-A10B-UD-Q4_K_XL:
    hf_tokenizer_for_model: ./models/tokenizers/Qwen/Qwen3.5-122B-A10B
    sampling: *id001
    cmd:
      cache-type-k: f16
      cache-type-v: f16
      model: ./models/Qwen3.5-122B-A10B-UD-Q4_K_XL-00001-of-00003.gguf
      ctx-size: 262144
      n-predict: 262144
