COMMON_FLAGS: &COMMON_CMD
  cache-type-k: q8_0
  cache-type-v: q8_0
  jinja: true
  parallel: 1
  cont-batching: true

QWEN3_SAMPLING: &QWEN3_SAMPLING
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 20

QWEN3_INSTRUCT_SAMPLING: &QWEN3_INSTRUCT_SAMPLING
  temp: 0.7
  min-p: 0.0
  top-p: 0.8
  top-k: 20

QWEN25_SAMPLING: &QWEN25_SAMPLING
  temp: 0.7
  min-p: 0.0
  top-p: 0.8
  repeat-penalty: 1.05

GEMMA_SAMPLING: &GEMMA_SAMPLING
  temp: 1.0
  min-p: 0.01
  top-p: 0.95
  top-k: 64
  repeat-penalty: 1.0

MISTRAL_SAMPLING: &MISTRAL_SAMPLING
  temp: 0.15

MISTRAL_THINKING_SAMPLING: &MISTRAL_THINKING_SAMPLING
  temp: 0.7
  top-p: 0.95

QWQ_SAMPLING: &QWQ_SAMPLING
  top-k: 40
  top-p: 0.95
  min-p: 0.0
  temp: 0.6
  repeat-penalty: 1.1
  dry-multiplier: 0.5
  samplers: top_k;top_p;min_p;temperature;dry;typ_p;xtc

GLM_SAMPLING: &GLM_SAMPLING
  temp: 0.6
  min-p: 0.0
  top-p: 0.95
  top-k: 20

GPTOSS_SAMPLING: &GPTOSS_SAMPLING
  temp: 1
  top-p: 1.0
  top-k: 0

GLM45_SAMPLING: &GLM45_SAMPLING
  temp: 0.6
  top-p: 1.0
  top-k: 0


healthCheckTimeout: 60

logLevel: info

models:
  Qwen3-8B-Q4_K_M:
    hf_tokenizer_for_model: Qwen/Qwen3-8B
    supports_no_think_toggle: true
    sampling: *QWEN3_SAMPLING
    aliases: [Qwen3-8B-NoThink]
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-8B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek

  Qwen3-30B-A3B-Instruct-2507:
    hf_tokenizer_for_model: Qwen/Qwen3-30B-A3B-Instruct-2507
    sampling: *QWEN3_INSTRUCT_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-30B-A3B-Instruct-2507-UD-Q5_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-30B-A3B-Thinking-2507:
    hf_tokenizer_for_model: Qwen/Qwen3-30B-A3B-Thinking-2507
    sampling: *QWEN3_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-30B-A3B-Thinking-2507-UD-Q5_K_XL.gguf
      ctx-size: 32768
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-Coder-30B-A3B-Instruct-1M:
    hf_tokenizer_for_model: Qwen/Qwen3-30B-A3B-Instruct-2507
    sampling: *QWEN3_INSTRUCT_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-Coder-30B-A3B-Instruct-1M-UD-Q5_K_XL.gguf
      ctx-size: 40000
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-32B-Think:
    hf_tokenizer_for_model: Qwen/Qwen3-32B
    sampling: *QWEN3_SAMPLING
    aliases: [Qwen3-32B-NoThink]
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-0.6B:
    hf_tokenizer_for_model: Qwen/Qwen3-0.6B
    sampling: *QWEN3_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-0.6B-Q4_K_M.gguf
      ctx-size: 32768
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-4B-Instruct-2507-UD-Q8:
    hf_tokenizer_for_model: Qwen/Qwen3-4B-Instruct-2507
    sampling: *QWEN3_INSTRUCT_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-4B-Instruct-2507-UD-Q8_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-4B-Thinking-2507-UD-Q8:
    hf_tokenizer_for_model: Qwen/Qwen3-4B-Thinking-2507
    sampling: *QWEN3_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-4B-Thinking-2507-UD-Q8_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  Qwen3-32B-SpeculativeDecoding-32768:
    hf_tokenizer_for_model: Qwen/Qwen3-32B
    sampling: *QWEN3_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Qwen3-32B-Q4_K_M.gguf
      ctx-size: 32768
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
      model-draft: ./models/Qwen3-0.6B-Q4_K_M.gguf
      gpu-layers-draft: 99
      draft-max: 8
      draft-min: 2
      device-draft: Metal
      ctx-size-draft: 8192


  gemma-3-1b-it:
    hf_tokenizer_for_model: google/gemma-3-1b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-1b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  gemma-3-4b-it:
    hf_tokenizer_for_model: google/gemma-3-4b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-4b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  gemma-3-12b-it:
    hf_tokenizer_for_model: google/gemma-3-12b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-12b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads: auto


  gemma-3-27b-it:
    hf_tokenizer_for_model: google/gemma-3-27b-it
    sampling: *GEMMA_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gemma-3-27b-it-q4_0.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  Mistral-Small-3.1-24B:
    hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
    sampling: *MISTRAL_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Mistral-Small-3.1-24B-Instruct-2503-UD-Q5_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  Magistral-Small-2507:
    hf_tokenizer_for_model: mistralai/Magistral-Small-2507
    sampling: *MISTRAL_THINKING_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Magistral-Small-2507-UD-Q5_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  Devstral-Small-2507:
    hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
    sampling: *MISTRAL_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Devstral-Small-2507-UD-Q5_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  Mistral-Small-3.2-24B:
    hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Base-2503
    sampling: *MISTRAL_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Mistral-Small-3.2-24B-Instruct-2506-UD-Q5_K_XL.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto


  # QwQ-32B-Q4_K_M:
  #   hf_tokenizer_for_model: Qwen/QwQ-32B
  #   sampling: *QWQ_SAMPLING
  #   cmd:
  #     <<: *COMMON_CMD
  #     bin: llama.cpp/build/bin/llama-server
  #     port: ${PORT}
  #     model: ./models/QwQ-32B-Q4_K_M.gguf
  #     ctx-size: 16384
  #     gpu-layers: auto
  #     threads:    auto
  #     parallel: 1

  QwQ-32B-Q4_K_M:
    hf_tokenizer_for_model: Qwen/QwQ-32B
    sampling: *QWQ_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/QwQ-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      model-draft: ./models/InfiniAILab_QwQ-0.5B-Q5_K_M.gguf
      gpu-layers-draft: 99
      device-draft: Metal
      ctx-size-draft: 8192
      draft-max: 8
      draft-min: 2


  # Qwen3-32B-SpeculativeDecoding-16384:
  #   hf_tokenizer_for_model: Qwen/Qwen3-32B
  #   sampling: *QWEN3_SAMPLING
  #   cmd:
  #     <<: *COMMON_CMD
  #     bin: llama.cpp/build/bin/llama-server
  #     port: ${PORT}
  #     model: ./models/Qwen3-32B-Q4_K_M.gguf
  #     ctx-size: 16384
  #     gpu-layers: auto
  #     threads:    auto
  #     reasoning-format: deepseek
  #     model-draft: ./models/Qwen3-0.6B-Q4_K_M.gguf
  #     gpu-layers-draft: 99
  #     device-draft: Metal
  #     ctx-size-draft: 8192
  #     parallel: 1

  # Mistral-Small-3.1-24B-SpeculativeDecoding:
  #   hf_tokenizer_for_model: mistralai/Mistral-Small-3.1-24B-Instruct-2503
  #   sampling: *MISTRAL_SAMPLING
  #   cmd:
  #     <<: *COMMON_CMD
  #     bin: llama.cpp/build/bin/llama-server
  #     port: ${PORT}
  #     model: ./models/Mistral-Small-3.1-24B-Instruct-2503-UD-Q5_K_XL.gguf
  #     ctx-size: 16384
  #     gpu-layers: auto
  #     threads:    auto
  #     model-draft: ./models/alamios_Mistral-Small-3.1-DRAFT-0.5B-Q5_K_L.gguf
  #     gpu-layers-draft: 99
  #     device-draft: Metal
  #     ctx-size-draft: 2048
  #     parallel: 1

  OpenCodeReasoning-Nemotron-32B-IOI:
    hf_tokenizer_for_model:   nvidia/OpenCodeReasoning-Nemotron-32B-IOI
    sampling: *QWEN3_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/OpenCodeReasoning-Nemotron-32B-IOI-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  OpenReasoning-Nemotron-32B-Q4_K_M:
    hf_tokenizer_for_model: nvidia/OpenReasoning-Nemotron-32B
    sampling: *QWEN25_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin: llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/OpenReasoning-Nemotron-32B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  OpenReasoning-Nemotron-7B:
    hf_tokenizer_for_model: nvidia/OpenReasoning-Nemotron-7B
    supports_no_think_toggle: true
    sampling: *QWEN25_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/nvidia_OpenReasoning-Nemotron-7B-Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek


  gpt-oss-20b-Q4-low:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q4_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"low"}'


  gpt-oss-20b-Q4-med:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q4_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"medium"}'


  gpt-oss-20b-Q4-high:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q4_K_XL.gguf
      ctx-size: 32768
      n-predict: 32768
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"high"}'


  gpt-oss-20b-Q8-low:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q8_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"low"}'


  gpt-oss-20b-Q8-med:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q8_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto


  gpt-oss-20b-Q8-high:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-20b-UD-Q8_K_XL.gguf
      ctx-size: 32768
      n-predict: 32768
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"high"}'


  gpt-oss-120b-Q8-low:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"low"}'


  gpt-oss-120b-Q8-med:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"medium"}'


  gpt-oss-120b-Q8-high:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-120b-UD-Q8_K_XL-00001-of-00002.gguf
      ctx-size: 32768
      n-predict: 32768
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"high"}'


  gpt-oss-120b-Q4-med:
    hf_tokenizer_for_model: openai/gpt-oss-20b
    sampling: *GPTOSS_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/gpt-oss-120b-UD-Q4_K_XL-00001-of-00002.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"reasoning_effort":"medium"}'


  GLM-4.5-Air-Q3:
    hf_tokenizer_for_model: zai-org/GLM-4.5-Air
    sampling: *GLM45_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/GLM-4.5-Air-Q3_K_S.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto


  GLM-4.5-Air-Q3-No-Think:
    hf_tokenizer_for_model: zai-org/GLM-4.5-Air
    sampling: *GLM45_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/GLM-4.5-Air-Q3_K_S.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto
      chat-template-kwargs: '{"enable_thinking": "False"}'


  GLM-4.5-Air-IQ4:
    hf_tokenizer_for_model: zai-org/GLM-4.5-Air
    sampling: *GLM45_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/GLM-4.5-Air-IQ4_XS-00001-of-00002.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto


  ERNIE-4.5-21B-A3B:
    hf_tokenizer_for_model: baidu/ERNIE-4.5-21B-A3B-PT
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/ERNIE-4.5-21B-A3B-PT-UD-Q5_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto


  EXAONE-4.0-32B:
    hf_tokenizer_for_model: LGAI-EXAONE/EXAONE-4.0-32B
    sampling: *GLM45_SAMPLING
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/EXAONE-4.0-32B-Q4_K_M.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto

  Apriel-1.5-15b-Thinker:
    hf_tokenizer_for_model: ServiceNow-AI/Apriel-1.5-15b-Thinker
    sampling:
      temp: 0.6
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/Apriel-1.5-15b-Thinker-UD-Q5_K_XL.gguf
      ctx-size: 16384
      n-predict: 16384
      gpu-layers: auto
      threads:    auto

  tinyllama-1.1b-llama-suite:
    hf_tokenizer_for_model: tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
    cmd:
      <<: *COMMON_CMD
      bin:  llama.cpp/build/bin/llama-server
      port: ${PORT}
      model: ./models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek

  tinyllama-1.1b-xQuant-llamacpp:
    hf_tokenizer_for_model: tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
    cmd:
      <<: *COMMON_CMD
      bin:  F:\LLMs\llama.cpp\build-ninja-user-release\bin\llama-server
      port: ${PORT}
      model: ./models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
      ctx-size: 16384
      gpu-layers: auto
      threads:    auto
      reasoning-format: deepseek
